== The Life of Ann Crowley

I have no expectation of leaving any thing that will bear the appellation of a journal,
but apprehending I should fail of manifesting that
gratitude which is due the Author of all good,
did I not transmit some account of the Lord`'s gracious dealings with me,
I am induced to make a few memorandums.
The remembrance of the multiplied mercies and abundant lovingkindness vouchsafed,
has often deeply prostrated my soul, and raised the language,
What shall I render unto thee, O God,
for the benefits and favours bestowed on thy unworthy servant?
When very young in years my mind was visited with the gentle reproofs of instruction,
and I felt, what I now believe was divine approbation,
when I acted agreeably to the religious precepts with which I was favoured,
before I knew it was the precious gift of grace thus operating on my heart.

I well remember some seasons of humiliation, when, in the depth of contrition,
I have kneeled down in my chamber, feeling the spirit of sweet supplication, though,
like Samuel of old,
ignorant of the voice of the Lord which influenced to this act of duty: and,
on rising from my knees,
I felt so happy that it led me to consider what should occasion such sweet,
peaceful feelings.
Through the teachings of the holy Spirit, I soon became sensible,
it was the influence of heavenly love on my heart;
and had I wisely kept near the all-sufficient gift of grace, I might, in early years,
have magnified the Lord`'s power,
by becoming a preacher of righteousness in life and conversation.
But, for want of dwelling with this blessed gift, and maintaining a constant watch,
the enemy of all good gained ascendency over my convinced judgment,
and I was miserably beguiled into an apprehension,
that I might indulge myself for a few years in the gratification of some worldly pleasures,
and afterwards submit to the cross and become a religious character.
This carnal reasoning brought death and darkness over my awakened understanding,
and I much lost the sense of those tendering impressions,
which had been mercifully experienced in the day of early visitation.
But thanks be to a gracious God, who kept me, in this season of revolt,
from all gross evil, and often followed with close conviction,
when indulging the vain mind,
in adorning the frail body with apparel inconsistent with the simplicity of the truth.
A fondness for dress and music were some of my greatest foibles;
and I am bound in gratitude to acknowledge, that had it not been for parental care,
advice, and prudent restraint, I might have gone great lengths in these gratifications.
Then, in the love of the gospel, I would most earnestly,
and most affectionately recommend all religious parents,
to be faithful in the discharge of their important duties,
remembering they are delegated as care-takers over a very important trust:
and happy will it be for those parents, who, in the day of righteous inquisition,
may stand acquitted in the divine sight,
having done all they could to preserve their offspring in true simplicity,
and in the fear of the Lord.

About the 16th year of my age,
I was renewedly favoured with a powerful visitation of heavenly love, by which,
through the tender mercy of a compassionate Father,
I saw there was no other way to obtain present peace and everlasting happiness, but,
believing in, and yielding obedience to,
the dictates of the Spirit of Truth revealed in the heart.
And as I gave up to follow the gradual unfoldings of the Lord`'s will,
I felt my strength increase to bear the cross and despise the shame,
and thus I began to understand, in my measure, the truth of that saying,
they that are faithful in the little, shall be made rulers over more.
I saw with indubitable clearness that Christ is the only "`way, the truth,
and the life;`" and that our words and our actions must be governed by his Spirit.
In this awakened state, my prayers were frequently put up in secret,
to the God and Father of all our sure mercies,
that his almighty presence might be as walls and
bulwarks around my fearful and trembling spirit,
to keep me steadfast in the faith, and watchful unto prayer:
that the enemy of my soul`'s salvation might not
again draw me aside from the simplicity of the truth,
as it is in Jesus, our only Redeemer and hope of glory.
As I was mercifully favoured to experience a change of heart,
and knew something of the new birth unto righteousness, I found him,
who was a liar from the beginning, very busy,
with insinuations suited to beguile into a disbelief of what I had now experienced,
of the blessed effects of religion on the heart.
Many were my conflicts, known only to an all-seeing God,
who compassionated my tried state,
and often caused the calming influence of his living presence,
to bring into a holy quiet, and humble trust, in which I felt sweet,
solacing peace to clothe my panting mind.

About the 17th year of my age, I met with a very close trial,
which involved my mind in deep affliction.
My tenderly beloved and honoured father,
who had been in a declining state of health for some years,
was suddenly removed from works to rewards, by an apoplectic fit.
At this time I was from home, and had been so for several months,
which increased my sorrow, from the reflection,
that I had thereby been deprived of the satisfaction
of fulfilling the last offices of filial duty,
and prevented the consolation of witnessing the peaceful close of an affectionate,
indulgent parent.
How unspeakably great is the loss which children sustain from the
departure of those who have tenderly cared for them,
as it relates to the preservation of the youthful
mind and the comfortable accommodation of the body.
How wise would it be, and acceptable to the great and good Parent of all living,
were those thus privileged,
daily engaged to seek after a right disposition to appreciate such blessings,
letting their deportment in all things, and at all times,
evince their sense of obligation for such unmerited favours.

After the death of my beloved father, I was much at home with my bereaved mother,
and such of my dear sisters as were then unmarried; endeavouring to comfort them,
as far as my small experience in the precious gift of true sympathy would admit:
we frequently mingled our tears together, and I have reason to believe,
it was a season of lasting profit to divers of us,
for which I now feel reverently thankful.
In the course of a few years, three of my sisters married,
which made a great chasm in our nearly united family,^
footnote:[Of seven sisters.]
so I may safely express myself,
having been favoured to live together in great harmony and tender affection,
the remembrance of which now yields solid satisfaction.
Many and various were the exercises of my mind about this time.
I often found the necessity of seeking, with earnestness of soul,
for wisdom and strength to conduct myself in all
respects agreeably to the profession I was making;
and many were the fears which assailed me, lest I should,
through any degree of unwatchfulness, mar the work which, in unutterable mercy,
was begun in my heart.
But in a sense of gratitude,
I may acknowledge the everlasting Counsellor did not fail to warn, instruct,
and grant the blessing of preservation,
so that faithfulness measurably kept pace with knowledge,
and my love to God was manifested by an endeavour to walk humbly in his fear,
which I found to be as a fountain of life, preserving from the snares of death.

In the second month, 1791, my much-loved sister Mary was, in the prime of life,
taken from the many comforts enjoyed by the humble, even in this probationary state,
I trust, to a far more happy and glorious inheritance,
where joys unalloyed are the blessed portion of the righteous forever.
She had been married only about a year and nine months,
and had many promising prospects to make her new sphere of life desirable.
But it pleased Infinite Wisdom to cast a shade over these pleasant pictures:
her health became delicate,
and very soon little hope could be entertained of her recovery,
which was a solemn consideration to me.
Truly "`The judgments of the Lord are unsearchable,
and his ways past finding out;`" but all his ways are perfect:
and thence we are instructed, that we have nothing to depend upon,
but his boundless mercy in Christ Jesus, our consolation and only hope of glory.
I can acknowledge, in a deep sense of manifold weaknesses,
that though this cup of sorrow was as the wormwood and the gall,
difficult to be drunk with becoming resignation, yet,
through the strengthening influence of all-sufficient Grace,
I could feelingly utter the submissive language of Job, "`The Lord gave,
and the Lord hath taken away; blessed be the name of the Lord.`"

Though this was a season of severe trial, yet upon a serious retrospect,
I can enroll it among those afflictions which have proved to me blessings in disguise,
and which have given occasion for the tribute of gratitude to be offered unto him,
who only knows what will tend to our sanctification,
and bring into the paths of enduring peace.
My soul can now, in tracing the wonderful dealings of an all-wise Providence,
lean upon the staff of faith, and worship him whose compassions fail not,
but are new every morning.
May it please him to continue his righteous judgments mixed with mercy,
all the days of my pilgrimage, that a preparation may be known, to offer,
in time and in eternity, adoration and praise, to his worthy name.

On the 6th of the fifth month,
we were visited by our truly valued friends Samuel Smith from America,
Hannah Wigham from Essex, Deborah Darby and Rebecca Young from Colebrook Dale,
Louis Majolier from France, Adey Bellamy from Wycomb, and John Hull from Uxbridge.
On the 9th they had a meeting at Warborough, which,
according to my infant state for judging, was a season of renewed favour,
in which I was divinely instructed.
In the afternoon they all left us, except Deborah Darby and Rebecca Young,
who stayed another night under my dear mother`'s roof.
They drank tea at my brother Saunders`', our family accompanying them,
after which a solemn silence prevailed,
in which some of our minds were deeply centred on God, the fountain of all good;
and after a season of reverent waiting,
these dedicated messengers of the Gospel were enabled to divide the word aright.
To my humbling admiration, much counsel and encouragement were handed in life and power,
reaching the witness in divers hearts, and raising the secret acknowledgment,
This is the Lord`'s doing, and it is marvellous in our eyes.
Oh! may I ever profitably remember his gracious dealings with me, a poor worm,
in the days of deep humiliation.

A proposal was made by one of these valuable friends,
that I should go with them to Farringdon.
The thought of having more of their profitable company seemed pleasant,
yet the prospect brought great awfulness over my mind,
insomuch that I was afraid to refuse, though there were feelings raised,
which were contrary to a quiet acquiescence,
because I apprehended the time was drawing near,
when my Divine Master would require a fresh proof of my love and obedience to him.
Yet I concluded it safest to go in simplicity;
and being favoured to feel a grain of that faith which removes mountains,
I ventured to accompany them to Abington,
where they had a meeting among the few friends of that place.
It proved a memorable season to me:
my mind was deeply prostrated during the whole time of our sitting together,
and I felt the love of God abundantly shed abroad in my heart,
insomuch that I could experimentally adopt the language of the Psalmist,
"`Thy people shall be willing in the day of thy power.`"
Yet so great was the fear that attended my mind,
lest I had not passed through the needful preparation to qualify rightly to minister,
and that by speaking, I should darken counsel by words without knowledge,
that I suffered the meeting to break up.

Though this brought my poor mind under renewed conflict,
yet I could appeal to my merciful Master, who knew it was not wilful disobedience,
but a fear of running before my spiritual guide;
so that I did not feel much condemnation in trying the fleece both wet and dry.
I spent an instructive evening with my companions,
who I believe were dipped into a sense of my condition.
The next morning we attended a meeting appointed by them at 11 o`'clock,
in which much exercise was renewed.

I was still fearful of believing myself called to so great and important a work,
as to become a minister of the everlasting gospel of peace and reconciliation;
and so struggled with doubt and fear till the meeting broke up.
This withholding more than was meet, appeared to shut up the way of my dear companions,
for public labour.
Indeed, I have believed,
since gaining a little more experience in the mysterious
ways and work of an Omnipotent Being,
that, in order to know the life and power to arise in our religious assemblies,
it is highly needful, for all the living members of the body,
to keep their ranks in righteousness,
whether it be in doing or suffering for the sake of the precious cause.

We all went to the house of our friend Robert Reynolds to dinner,
but my mind was too deeply exercised to take much nourishment for the body;
for truly I desired, above all other considerations,
that it might be my meat and my drink, to do the will of my Heavenly Father.
After dinner many Friends came in, nearly all we had sat with at meeting:
a solemn silence soon prevailed,
the mighty power of Truth seemed eminently to overshadow our little gathering,
and many minds were much humbled; in which precious feeling I was made sensible,
that was the accepted time for the offering to be made.
I ventured to stammer forth a few expressions;
which arose in that degree of life and power, that no doubt remained,
it was the operation of Divine love which influenced me
to yield to the fresh manifestation of revealed duty:
and Oh! the blessed reward of peace that flowed into my humbled heart!
Language is inadequate to describe this heavenly
enjoyment! but it will be fully comprehended by those,
who have tasted the sweet fruits of obeying the commands of our Heavenly Father,
in small as well as greater requisitions.
I now believed it best for me to return home,
which I did under solemn impressions and serious considerations:
for although my mind was favoured with a rich reward, yet I began to consider,
that I had now put my hand to the plough.
I remembered what was declared in the Scriptures, that those who had done so,
and looked back, were not tit for the kingdom.
I very forcibly felt the weakness attached to humanity,
and knew the aptitude in frail mortals to shrink from the cross of Christ,
and it was suggested to my mind,
that I should never more be clothed with so much
strength to fulfill my heavenly Father`'s will,
if another offering of the like nature should be required:
and I was closely tried with another suggestion;--what
would my relations and friends think,
of my thus becoming a public spectacle, by speaking in the assemblies of the people.
Thus the enemy to my present and future happiness used many means to discourage me;
but Christ, our great High Priest, who is touched with a feeling of our infirmities,
did not fail to succour in the needful time;
and by the fresh incomes of his love and life,
caused these unprofitable cogitations to be silenced in my troubled heart,
and gave fresh ability secretly to acknowledge his Almighty power,
so that my mind overflowed with a portion of that joy which is unspeakable.
I kept my exercises much within my own breast,
as I had been divinely instructed to do so,
from the very early time of knowing any thing of the work of grace on the heart.

On the fifth-day after my return home, I attended, as usual, our week-day meeting.
When I took my seat, I felt the gathering arm of Divine love,
and my mind was soon centred in solemn, awful silence; in which precious state,
I intelligibly heard, as I apprehended,
the still small voice of my great Lord and Master, requiring public expression:
and in great brokenness and fear, I uttered a few words,
which then livingly opened in my mind, and sat down in the enjoyment of much peace.
But, before the meeting broke up,
I began to think what would become of me when we separated;
for my nature dreaded to become a fool, even for Christ`'s sake:
such is the weakness of the human mind,
when even but a little from under the influence of that Almighty power,
which makes the Lord`'s people willing to do or suffer for his blessed name`'s sake.

My way was easier than I expected, for my friends spoke kindly after meeting,
evincing their having felt sympathy with me, and unity with my offering;
but these tokens of love and approbation, had no tendency to exalt the creature,
for my mind was then deeply humbled under many considerations and varied dispensations,
wisely permitted to keep the heart in subjection
to the will of its great Creator and preserver.
In this season of deep and complicated exercise, I kept much at home, loving retirement,
and often sought opportunities to wait on my Heavenly Counsellor, and holy leader;
who condescended to prove himself strength in weakness, riches in poverty,
and a present help in the time of need.

I truly found him to be unto poor me, the source of all-sufficiency,
while my mind was preserved in a humble dependence on his eternal arm of power.
But in unsearchable wisdom he at times saw meet to try my faith and confidence,
by withdrawing the sensible perception of his love
and life,--the precious enjoyment of him,
in whose presence my soul delighted; when I was ready to adopt the language, "`Tell me,
oh thou whom my soul loveth, where thou feedest,
where thou makest thy flock to rest at noon:
for why should I be as one that turneth aside,
by the flocks of thy companions;`" but endeavouring
to keep in the stillness and nothingness of self,
seeking above all things to attain, in my measure,
to that state of humble acquiescence which enabled the experienced apostle to say,
"`I have learned in whatsoever state I am, therewith to be content.`"
I found this to be an attainment worthy a Christian`'s aspiring after;
as it ever proves balm to the troubled soul, and fortifies it in the day of affliction,
so that under the dispensations attendant on a state of Christian warfare,
a capacity is renewed, to breathe the emphatic language uttered by our blessed Exemplar,
"`Not my will, but thine be done.`"

On the 26th of eleventh month,
our friends Martha Haworth and Priscilla H. Gurney came to my mother`'s,
and had a meeting that evening at our meeting house, which was, I thought,
evidently owned by the Minister of the sanctuary:
they had also a religious opportunity in my mother`'s family,
to our edification and comfort:
thus I was often reminded of the great privilege of having parents who
delighted to open their houses and hearts to the Lord`'s messengers.
I have frequently been led to believe,
that if parents and heads of families were sufficiently sensible
of the advantage it is to a young and rising generation,
to have the instructive company of solid, experienced friends,
they would not let little family incumbrances, or domestic cares,
prevent their readiness to entertain travellers,
who are sent with a gospel message of glad tidings to the meek and lowly of heart,
and to the stirring up the pure mind by way of remembrance
of our religious and social duties.
And if the beloved youth were desirous of gaining instruction
and profitable impressions from such visitors,
they would endeavour to make the way easy to their parents
thus to evince their love to the cause of truth,
by cheerfully entertaining its advocates.
With gratitude I may acknowledge my belief,
that many amongst us are manifesting this laudable disposition:
and I cannot doubt but in due time they will receive an ample reward.

When these friends left my mother`'s house,
with her approbation I accompanied them to a few meetings.
In some of them my way was mercifully opened,
to relieve my mind of much exercise which had attended it for some time.
In a few days I returned home, with the sheaves of peace in my bosom,
for this act of dedication.
How richly does the Almighty reward, for endeavouring to walk in his counsel,
and live in his fear!

[.small-break]
'''

1793+++.+++ I went to Witney to pay a social visit to my relations,
during which time our quarterly meeting for Oxfordshire was held at that place.
We were favoured with the instructive company of a deeply experienced minister.
Oh, the sweet and precious unity which is felt by kindred spirits!
They may be much strangers to each other as to outward knowledge or communication,
but the cementing power of truth is to be known in solemn silence;
and whether thus known, or by outward communication,
it will ever be the privilege of true Christians,
while they are concerned to keep their ranks in righteousness:
for this is that fellowship which is with the Father, and with the Son,
and with the household of faith the world over.

On the 12th of fourth month, I returned to Witney, where I stayed some months,
during which time my mind was often gathered from all visibles, into an awful,
silent waiting upon the everlasting Counsellor, and Preserver of those,
who depend upon divine aid; and, blessed be his name,
he graciously condescended to instruct my panting
mind more fully in the nature and excellency of pure,
undefiled religion: and had obedience at all times kept pace with knowledge,
I might have been a more able advocate for that cause which is dignified with immortality,
and crowned with eternal life.
In this season of the Lord`'s power, in which self was measurably abased,
my mind was brought into exercise,
under which I could tenderly sympathise with those who rightly
embrace the principles and practice of our religious Society,
faithfully bearing the cross, in using the plain language, etc.
Oh! how frail is the poor finite creature,
when from under the blessed influence of that Holy Spirit,
which reduces the will of unregenerate man,
and brings into subjection to the cross of Christ.
Then, if strict watchfulness is not maintained,
there is an opportunity for the enemy to cast in discouragement,
and tempt us to call in question the requisition of duty,
even to withholding the sacrifice: and if,
from an unwarrantable desire to make our way more easy,
we ask counsel of our fellow travellers, instead of patiently waiting for help,
from that Almighty Being who can break all our bonds, and enable us to fulfill his will,
we shall find this will weaken instead of strengthening the grain of remaining faith.
May, then, the sincere in heart, who hear or read this remark,
be careful to keep the eye single to the Captain of their salvation,
who is able to bring through every exercise and trial of faith,
to the honour of his great name.

After my return from Witney I stayed several months under my dear mother`'s roof,
attending meetings for worship and discipline as they came in course,
esteeming it a great favour, when health would permit,
to enjoy the privilege of quietly assembling with my friends, to wait upon Almighty God,
who, through his Son Jesus Christ, revealed,
as far as I had a spiritual capacity to understand, the mysteries of redeeming love,
unfolding them in the renewed light of his own Eternal Spirit,
by which we are made wise in things that are truly excellent, and by obedience,
become the happy partakers of "`joy unspeakable and full of glory.`"

[.small-break]
'''

Fourth month 13th, 1794,
I left my peaceful home in order to attend the Half-year`'s meeting held at Newtown,
for the principality of Wales.
In this journey I was very satisfactorily in company with Mary Stevens of Staines,
and our much valued friends George Dillwyn and wife.
I felt it a great trial to part with my truly affectionate, aged mother,
who was in delicate health: her solicitude for my preservation was cordially felt;
and though, in her weakly state,
it seemed a trial to have the prospect of a wide separation from
one of the objects of her maternal care and tender solicitude,
yet she was very cautious not to raise any discouragement in my often tried mind,
but endeavoured kindly and affectionately to strengthen
my feeble heart to fulfill apprehended duty.
And it is in a sense of unmerited favours,
received from the eternal Source of all effectual help, that I can feelingly acknowledge,
divine love was graciously extended in every hour of need,
and faith was given to believe, and confide in the efficacy of Almighty power.
In this journey I travelled more than 300 miles, attended 30 meetings,
and was absent from home three weeks and four days.

[.small-break]
'''

After my return from this little service, I was much at home,
until the 22nd of second month, 1795,
when I went to London to attend the funeral of my dear cousin Mary Crowley,
which was to me a solemn and profitable season.
From London I went to Staines, where I had proposed to spend a little time;
but soon after my arrival there,
I received the sorrowful account of my beloved and
honoured mother being seized with a paralytic stroke,
which much affected her limbs, speech, and memory.
This mournful intelligence hastened my return home,
and I was thankful to find her living and sensible,
and esteemed it a great favour to have the privilege of aiding my dear sisters,
in fulfilling the offices of filial duty,
in wailing upon and caring for our beloved parent,
who continued under much bodily suffering until the 10th of sixth month;
when the spirit took its flight from the afflicted tabernacle, to be centred,
I humbly trust, in the realms of undisturbed rest and peace,
employed in singing the angelic song of "`Salvation, and glory, and honour, and power,
to the Lord our God!`"

This very affecting dispensation much increased the trial of my faith and obedience,
for I was at this time under religious exercise, produced by an apprehension,
that it was required of me to give up to a weighty and important
prospect which had long attended my mind,
to pay a visit to Friends of the counties of Worcestershire, Warwickshire,
and Hertfordshire.
The thought of leaving my much loved sisters so soon
after experiencing the loss of our dear mother,
was a close trial, as I was the eldest who resided at home,
and consequently would be expected to take the largest
portion of management in settling domestic affairs.
But this consideration did not relieve my mind from
the weight of exercise that had long attended it,
nor could I see any other way to attain that peace which
was more desirable to me than any worldly enjoyment,
than by passively giving up to what I believed to be a divine requisition.

Therefore, in a few weeks after the interment of my beloved affectionate mother,
I laid the prospect before my friends, at our Monthly meeting,
at which we unexpectedly had the company of our valued
friends Sarah Harrison and Sarah Birkbeck,
which was a great strength and comfort to my poor feeble mind.
They were dipped into near sympathy with me,
and expressed full unity with my religious concern; also proposed our uniting in it,
as they were then proceeding to visit Friends, in two of the above-mentioned counties.
This was a great comfort to me, as I had no companion in view: accordingly,
after obtaining my certificate, I joined them in Warwickshire,
and we proceeded together in near unity, through that county, and also Worcestershire,
when our minds were unexpectedly drawn towards the inhabitants of the Isle of Man,
which was a renewed trial of my faith,
and caused many cogitations to attend my doubting mind.
I suffered reasoning so far to prevail,
that darkness and distress became the covering of my spirit;
but through the never-failing mercy of my compassionate Leader,
I was reduced into a willingness to join in the apprehended requisition,
and wrote to my friends at home for their concurrence; but this I did not venture to do,
being very jealous over my own feelings and judgment,
until I had requested some friends of religious experience,
to sit down with me to weigh this important concern;
and a confirming satisfactory opportunity we were favoured with,
which greatly relieved my mind.
I soon received a certificate from my own monthly meeting,
expressing their tender sympathy and unity with my prospect.

Thus, being set at liberty according to good order,
we embarked at Liverpool the 9th of ninth month,
and had a tedious voyage of two nights and nearly three days.
We had about 80 passengers on board, many of whom were dissipated characters,
whose unchristian conduct caused us sorrow;
but we were comforted by having the sympathizing company of some weighty friends;
Richard Reynolds, Robert Benson, and Isaac Hadwin were of the number,
who were all kindly attentive to us.
We arrived safe on the island in Castleton, where, on the following day,
we had a large satisfactory meeting; after it, went to Ballassy, Peel Town, Kirkmichal,
Ramsey, and Douglas, having meetings at each place.

Feeling our minds set at liberty, we took shipping for Whitehaven, the 25th,
and had a pleasant and quick voyage,
for which we felt truly thankful to the Preserver of men,
who had graciously evinced his power in our weakness.
We found considerable openness in the minds of many in that small island,
to receive gospel truths: divers manifested much tenderness of spirit,
the behaviour of the lower class was civil and kind,
great hospitality and readiness to accommodate us was shown
by many among the first rank in worldly possessions,
some of whom appeared to receive the visit of love with thankfulness;
so that we had cause gratefully to believe the Holy Head and High Priest,
had prepared the way for the poor servants to occupy with their gifts,
in proclaiming the glad tidings of the everlasting gospel of life and salvation:
in the heart-tendering sense whereof,
we were enabled to return the tribute of praise to him in whom is all-sufficient help.

The day after our arrival at Whitehaven I felt at
liberty to leave my endeared companions Sarah Harrison,
Sarah Birkbeck, and Priscilla H. Gurney, and,
accompanied by our friends Robert Benson and Isaac Hadwin, proceeded to Liverpool,
taking a few meetings in the way.
Here I took my own horse and chaise,
and went forward to accomplish the remainder of the visit to Friends in Herefordshire.
Mary Beesley kindly accompanied me till we got to Worcester, where we parted,
after having a memorable meeting,
for which service I had been previously introduced into much conflict of mind.
From that meeting I pretty directly journeyed homeward,
taking but few meetings in my way, and was favoured to reach my own habitation,
then at Shillingford in Oxfordshire, in safety, the 15th of tenth month,
after an absence of three months and three weeks,
having travelled in this journey upwards of 900 miles, and attended 63 meetings,
and have now thankfully to acknowledge, to the praise of my great and good Master,
that preservation was not withheld.

[.small-break]
'''

On my return home, I had fresh trials to encounter.
It now became needful for my sisters and myself to consider
the propriety of our continuing in the same place,
or dwelling, our much loved mother left us in, or to seek a new situation.
This became a very serious subject to me,
as I felt it to be of great importance to our preservation
and growth in things most essential,
where we should fix our place of residence.
This source of anxiety, with some others of equal weight,
which then pressed down my mind, as I believe, occasioned a severe fit of illness,
which reduced the bodily powers so much,
as to leave little or no hope to my relatives and friends of my recovery,
or continuing long in mutability.
But in the midst of very great bodily weakness,
when my strength was so far reduced as not to be able to articulate,
I believed that my Divine Master had more service
for me before the day`'s work would be accomplished.
This apprehension was soon realized; for it proved the crisis of the disease,
which was inflammation on the lungs.

From this time, in a few weeks I recovered my strength,
so as to be able to attend our Monthly meeting,
where I opened the concern that had so weightily impressed my mind.
From severe indisposition and long confinement, I was reduced to such a low, weak state,
as induced some of my friends to query the probability of
my being able to accomplish the prospect before me,
of visiting Friends of Buckinghamshire, Bedfordshire, Hertfordshire,
and Northamptonshire: yet the evidence mercifully granted,
strengthened their sympathizing minds to set me at liberty.
This tended to my relief,
and enabled me to turn my attention to the serious consideration
of my beloved sisters and myself moving to Uxbridge,
the place in my apprehension pointed out, in the wisdom of truth, for us to remove to,
as a present residence:
and though there were many circumstances which rendered such a step difficult,
yet the evidence graciously afforded, was so indubitably clear, that I dared not,
in the most proving season, call in question the rectitude of such a movement,
though many of the Friends of our own meeting were ready
to think us wrong in leaving the place of our nativity.
This was a close trial to me, as I much valued the judgment of my friends,
and consider it one among the many privileges attached
to membership in a religious society,
to be cared for and counselled as occasion may require,
both in religious and civil concerns; and I can truly say,
it greatly increased my love and esteem for my friends,
whenever they manifested such care for my welfare, though, in this instance,
I have cause to believe our moving was in the counsel of unerring wisdom.

As I wished to leave my dear sisters as free from incumbrance as I could,
we judged it best to remove before I left them: accordingly, we made speedy preparation,
and soon effected our plans.
About two weeks after our removal to Uxbridge,
I took leave of my beloved sisters the 29th of ninth month, 1796,
and entered on a visit to the counties before mentioned,
accompanied by my endeared friend Elizabeth Raper, who had a similar concern.

We travelled harmoniously together in this important engagement:
and though we felt greatly humbled under the consideration of inexperience,
and want of capacity always to "`divide the word
aright,`" yet in the winding up of this little service,
we had gratefully to acknowledge the Lord`'s gracious dealings with us,
that our compassionate High Priest had, beyond our expectation,
proved to his feeble servants, mouth and wisdom,
tongue and utterance and the source of all-sufficiency.
In this journey we travelled 550 miles, attended 56 meetings,
and visited families in several places.
In some of these engagements, we had the strengthening,
instructive company of Rudd Wheeler, of Hitchin; and I may acknowledge with thankfulness,
the reward of soul-enriching peace was granted.

[.small-break]
'''

In about three weeks after my return I met with a very close trial,
in the death of my beloved sister, Catharine Ashby, wife of T. Ashby, of Staines.
Her removal was deeply felt by her relatives and friends,
to whom she had much endeared herself by a meek and quiet spirit.
Her disposition was tender and affectionate,
ever ready to administer help and comfort to those who stood in need:
humility and godly sincerity were conspicuous traits in her character;
and although the prospect of leaving an affectionate husband
and six small children (one a babe) was trying to her feelings,
she was enabled, in true resignation, to commit them to the care of her heavenly Father,
with humble acquiescence in his will,
taking leave of them all with great composure and sweetness, advising the two eldest,
who were the only ones capable of receiving counsel from her dying lips,
to endeavour to be good, obedient children,
and attend to the advice of those who had the care of them.
This afflictive dispensation brought fresh care upon my sisters and myself,
as it became our duty to take the place of a departed mother,
as far as we were enabled to do so; which brought us to the trial of separation,
one of us mostly residing with our bereaved brother-in-law and the dear little children,
endeavouring to comfort them under the loss of maternal tenderness and care.
It was not my lot to take a large share in the active part of this service;
for in the 17th of seventh month, 1797, I left home to accompany Phebe Speakman,
a Friend from Concord in Pennsylvania,
who was on a religious visit to Friends of this nation.

We travelled harmoniously together, through most of the counties in England,
Scotland and Wales, in which laborious engagement,
I experienced many close exercises and deep baptisms, knowing at times,
what it was to want the sensible evidence of divine love and life,
in which my faith was proved; but through unutterable mercy, could also say,
that seasons were granted,
in which the aboundings of heavenly light and consolation were my blessed experience,
and strength was graciously afforded to testify to
the goodness and mercy of an Almighty God,
who is not a hard master, but grants a rich reward to the humble, dedicated mind,
for every act of faithfulness.

In this journey we travelled more than 4000 miles, attended 397 meetings,
and visited Friends in many families,
much to the relief and satisfaction of our own minds, although, in the winding up,
we could truly say, we were but unprofitable servants, and had need of patience,
that we might inherit the promises.
While in this arduous service, I took a violent cold,
which produced inflammation on the lungs, and,
with the effect of fatigue and much exercise, reduced my strength so much,
as to leave little prospect that the enfeebled frame would be again restored to health;
and I was willing to hope that my heavenly Father might see meet
to loose the tribulated spirit from a very afflicted tabernacle;
but it pleased Him, after proving my faith and patience, to raise me up,
and fresh ability was granted to resume the line of apprehended duty.
I again united with my endeared companion Phebe Speakman, in religious labour,
after having been confined three months at the house
of our much-loved friends Lindley and Hannah Murray,
at Holdgate near York.
The unremitting kindness and great hospitality of these worthy friends,
to one of the least of the Lord`'s messengers, was cause of humble admiration;
how did their Christian conduct sweeten the bitter cups handed in unfathomable wisdom,
doubtless for purifying the vessel, that it might be more fit to receive, and retain,
the pure oil of heavenly consolation.
In remembrance of these favours, humble thankfulness is raised,
and the grateful language has arisen, "`What shall I render unto thee.
Oh Lord! for all thy benefits?`"

[.small-break]
'''

After this journey, which closed in fourth month 1799, I continued much at home,
except occasionally attending some neighbouring Monthly and Quarterly meetings.
On the 14th of Eighth month 1801,
I entered upon a religious visit to Friends of the counties of Hants, Dorset, Devon,
Somersetshire, and Cornwall, accompanied by my former beloved companion Elizabeth Raper.
In this journey we travelled 1266 miles, attended 115 meetings,
and visited many families; and though, in retrospect,
"`I remember the wormwood and the gall,`" yet in
commemorating the Lord`'s dealings with us,
who were as babes in his school, the humble acknowledgment is raised in my heart,
that the Lord is good to those that fear his name,
and endeavour to walk steadfastly and faithfully in his counsel.

I was absent from home five months and two weeks;
and though many trials attended so long a separation from beloved sisters and friends,
my good Master sweetened the bitter cup, by his life-giving presence.
After this journey I was mercifully favoured with
a peaceful release from much public engagement,
except attending some neighbouring Quarterly, Monthly, and Preparative meetings,
until the fourth month, 1802, when I attended the Half-year`'s meeting in Wales,
held in Newport, accompanied by my beloved friends, John Hull, William Hull and wife.
We travelled very agreeably together, about 400 miles, took several meetings,
going and returning, much to my relief, and I hope to mutual satisfaction, and could say,
on arriving at our own quiet habitation, that it is good to attend, in simplicity,
to the gentle leadings of the Spirit of Truth.

[.small-break]
'''

After some months`' enjoyment of the consoling society of near relatives and friends,
my mind was impressed with an apprehension,
that the right time was come for me to enter upon another religious engagement,
which had long laid weightily on my spirit,--to visit the meetings
constituting the large Quarterly meeting of London and Middlesex.
Accordingly, after informing my Monthly meeting, and obtaining their approbation,
I entered on the visit, accompanied by my much loved friend, Deborah Moline.
We attended each Monthly and Particular meeting;
in which weighty engagement my mind was often reduced to a very low state,
baptised into death, and suffering; but,
by an honest endeavour to abide with the gift of grace, in patience and confidence,
I was mercifully favoured, at times, to feel the arising of that Almighty power,
which can alone enable the poor instruments to minister in any degree,
in the demonstration of the Spirit of Jesus Christ, the great Minister of ministers,
and Bishop of souls; who, presiding as High Priest,
qualifies his dependent servants at seasons, to testify, through blessed experience,
that Truth reigns over all,
and would overcome all that stands in contrariety to the
purity and righteousness of his everlasting kingdom.
I have thankfully to acknowledge,
that a sweet reward of peace was graciously afforded for obedience to manifested duty.
In the winding up of this labour of love, I could feelingly adopt the language,
"`Return unto thy rest, Oh my soul! for the Lord hath dealt bountifully with thee.`"
Verily, it is good to put our whole trust in him,
who is the fountain of wisdom and strength,
who does not fail to prepare and qualify for his service,
according to the purposes of his righteous will.

[.small-break]
'''

After this engagement I was permitted to rest at home until the winter of 1804, when,
in company with my beloved friend, Susannah Home,
I paid a religious visit to the families of Friends, belonging to my own Monthly meeting;
and, in condescending mercy, we were enabled to say,
that when the great Head of the church is pleased to put his servants forth,
he does not fail to go before, and prepare the way,
to the humble admiration of those who trust in him,
and are careful to follow the leadings of his Holy Spirit,
even into paths they have not seen, or before trodden.

From a desire to be found faithful to divine requisitions,
my mind became willing to yield to a fresh discovery
of what I believed to be the Lord`'s will,
though it cost me much.
For in addition to the baptisms needful to qualify for service,
I was much proved in the prospect of again leaving home,
as my beloved sister Saunders was in a declining state of health,
not likely to survive many weeks;
but I remembered it is declared in the Scriptures of Truth,
that those who love any thing more than Christ, are not worthy of him;
and I endeavoured to seek after resignation to the will of my heavenly Father,
trusting in his goodness and mercy.
Although I had the unspeakable trial of leaving my sister,
the dear object of my tender solicitude, to join my former beloved companion,
Susannah Home, in a visit to Friends of the counties of Surrey and Sussex,
and to hear the sorrowful tidings of her final departure,
a short time after my leaving home, yet I dared not repine, or think it a hard allotment,
that I had been made willing to leave all that was near and dear, in natural ties,
to follow my Lord and Master; for I found, to my unutterable consolation,
that his holy presence and approbation made hard things easy, and bitter things sweet.
I was thankful in feeling at liberty to return for a few days,
to pay the last tribute of love and affection to so near a relative;
and after a solemn farewell to mournful connections, I joined my dear companion again,
in Surrey, and found her sympathy and unity very precious, in this season of trial.
We travelled harmoniously together, through the before-mentioned counties,
when it appeared right for us to part,
as Susannah Home`'s prospect did not extend further,
and my view had been to Friends of Kent also.

The thought of separating from one qualified to share in the labour of the day,
before the mission was fully accomplished, was trying to nature;
but I felt a care not to encourage her to go further than she was required,
believing it to be very unsafe for those who are called to public service,
in the militant church, to exceed their commission, from the bias of sympathy and love,
which they may feel towards those with whom they have been united,
unless a liberty be sensibly felt, to accompany a fellow traveller.
Truly the ministers of the gospel have need to know on what ground they are treading;
for nothing but the sure foundation will sustain in the day of trial,
when faith and patience are reduced to a low ebb, by varied conflicts, which,
I believe is often the experience of the Lord`'s servants,
who are called into the field of labour.
In the hope that we were acting according to best wisdom,
we parted in near unity and love.
Dear Susannah Home returned home,
and I proceeded to take the meetings of Friends in Kent,
my beloved friend Elizabeth Moline, going with me.
In this journey, I travelled upwards of 400 miles,
attending all the meetings in the several counties.

[.small-break]
'''

It did not seem consistent with the will of my heavenly Father,
that I should rest long at home; for in the sixth month of the same year,
I apprehended it was required of me, to unite with my former dear companion,
Susannah Home, in a visit to Friends in the counties of Essex, Suffolk, Norfolk, Lincoln,
Yorkshire, Durham, Northumberland, Cumberland, and Westmoreland.
In this arduous journey, we travelled nearly 3000 miles, attended 241 meetings,
and visited 627 families.
Such an engagement required deep baptisms, to prepare for usefulness,
in the great Master`'s time, doing or suffering according to his unerring wisdom;
but by endeavouring patiently to bear these descendings, we were permitted, at seasons,
mercifully to feel the renewed arisings of light and life, in which alone,
qualification is received to divide the word aright,
so as to reach the witness in the hearts of the hearers.
I was graciously dealt with in this religious engagement,
and had frequently to adore the Lord`'s never-failing goodness.
My mind is bowed in the fresh remembrance of his gracious dealings with me,
a poor unprofitable servant, who can feelingly acknowledge,
it is the work of God alone that can praise him,
and that he remains worthy of all worship and adoration,
for "`his mercies are new every morning.`"
I was favoured to return to my habitation, with the sheaves of soul-enriching peace,
the 26th of fourth month, 1806,
and had the inexpressible comfort of finding my dearly beloved sisters in usual health,
and capable of joining with me in grateful acknowledgment for the blessing of preservation.

[.small-break]
'''

The three following years I spent much at home,
except attending a few neighbouring meetings.
My health had suffered considerably by long exposure to northern blasts,
during an unusually severe winter,
that I deemed it a favour to feel a peaceful release from travelling;
and much desired that my time might be usefully filled up in different engagements;
but have now feared it has not been so fully devoted to good purposes,
as it might have been, had I been more watchful and weighty in spirit.
O! how frequently do I lament my manifold deficiencies,
and grieve that the gifts of a beneficent Father,
should not have been more fully occupied to the glory
and honour of the all-bountiful Giver,
the real edification of the church,
and the sanctification of that immortal part which must exist to a never-ending eternity.
Did I not believe in the mercy and forgiveness of a gracious God, through Christ Jesus,
upon sincere repentance, great would be my distress of mind;
but I thankfully know from blessed experience,
that his compassion faileth not towards those who love his judgments,
and can gratefully receive his reproofs of instruction.

[.small-break]
'''

In 1810, I engaged in a religious visit,
accompanied by my endeared friend and fellow-labourer Priscilla H. Gurney,
in the counties of Essex, Suffolk, and Norfolk.
We attended the Quarterly meetings, had fifty-two meetings in the three counties,
and visited families in several of them.
During most of this journey my health was in a very feeble state;
but through the renewings of divine help,
I was mercifully favoured to accomplish this labour of love, much to my own relief, and,
I humbly trust, to mutual edification.
We found great openness in the minds of Friends pretty generally,
to receive such counsel as appeared to us to open in the renewings of light and life;
and I sincerely hope the blessed truth did not suffer
by our simple endeavours to exalt and support it,
and the precious testimonies given us to bear, by a crucified Lord and Master,
whose reward is with him, and his work before him.
Many were the baptisms and exercises during this engagement,
but the Lord condescended to prove himself the stay and strength of his little ones,
who desire to trust in Him alone.
Our minds were sweetly united in gospel love,
and we were favoured to labour harmoniously together, according to the gifts received,
to our true peace; though we could feelingly make the acknowledgment,
we are but unprofitable servants.
Under a sense of my manifold weaknesses and infirmities, I was often led to exclaim,
it is mercy,--mere mercy, that I am yet preserved, a monument of the Lord`'s power;
through whom alone any works are wrought which magnify his excellent name,
and edify the body, of which Christ Jesus is the Head.
I had found him to be strength in weakness;
so that I could say with the disciples of old, when queried of by their Divine Master,
"`When I sent you out without purse or scrip, lacked ye anything?
they answered, '`Nothing, Lord!`'`"

After this, I was permitted to rest in the society of dear sisters and friends,
for several months, except attending a few of the neighbouring meetings.
This I esteemed a great favour, as my much loved sister Rebecca,
was in a debilitated state of health; and I felt it a great privilege,
to share with my other sisters, in waiting upon her;
having often experienced the close trial of leaving this
dear object of solicitude under great bodily suffering,
when I have been instructed and strengthened by what our blessed Saviour said,
"`He that loveth any thing more than me is not worthy of me.`"
It is verily a great attainment to know the will of the
creature brought into subjection to the divine will,
so as to be able to say from living experience,
It is my meat and my drink to do thy will, O God!
Yet my mind was frequently tried with dismay, lest, as the apostle said,
"`After having preached to others, I myself should be a castaway.`"
But these seasons were, doubtless, for my further refinement,
inciting to watchfulness unto prayer; for human nature is frail;
and it is an unspeakable favour to have the reproofs of instruction sounded in our ears,
in any way that unerring wisdom sees most likely
to quicken our diligence in the work of our day,
of which I consider watchfulness and true heart-felt prayer, a material part.
How emphatic are the words of our dear Redeemer, "`What I say unto you, I say unto all,
watch!`"

[.small-break]
'''

First month, 1812.--For some considerable time before this date,
my mind had been closely impressed with a belief,
that it was required of me to pay a religious visit to our large Quarterly meeting,
both meetings for worship and discipline, and many of the families.
The prospect felt very weighty, and the importance of the engagement such,
that I was often led secretly to exclaim "`Who is sufficient for these things?`"
but I remembered him who had mercifully led about, instructed, and preserved,
in former religious services, and could say,
in grateful recollection of his wise and gracious dealings with me,
a poor weak instrument, "`Not my will, but thine, be done,`" Oh thou,
whose judgments are a great deep,
and whose ways are unsearchable to the human understanding!
Under these considerations I bowed in submission;
and believing the time to be fully come,
I cast the prospect before my friends in godly fear,
and proposed to my much loved friend, Lydia Forster,
to accompany me through this service, if she felt freedom in the liberty of the truth.
After some time of solid deliberation she felt most easy to unite in the proposal,
which met the full concurrence of our friends,
who set us at liberty to pursue our prospects, as way might open in unerring wisdom.

We left home the 24th of second month, 1812,
and parting with our near relations and friends in the precious
feeling of gospel union and heavenly love;
the remembrance of which was a balm to our tried minds,
when faith was reduced to a low ebb.
Oh, how consoling is true heart-felt sympathy! verily there is strength in love,
and fellowship in suffering.
This religious embassy engaged us till the 27th of fourth month,
when we were favoured to feel a peaceful retreat, after having endeavoured,
according to the small ability possessed, to keep our ranks in righteousness,
and fill up our measure of suffering for our great Master and the church`'s sake:
and though feelingly adopting the language,
"`We are unprofitable servants,`" yet we could say
the Lord`'s strength was made perfect in our weakness.
The suffering I endured from frequent indisposition and a weakly constitution,
though trying to bear, was scarcely worthy of notice,
compared to what our predecessors underwent,
in paying similar visits of gospel love to their brethren and sisters,
when they were haled to prison, suffered cold, hunger, and hardships, which we,
in this day of ease, are scarcely able to comprehend.
Oh then, my soul, mayest thou, with all the Lord`'s servants,
be willing to follow a gracious Master in the way of his leadings,
and faithfully obey his righteous commands,
though it be ever so repugnant to thy own will.
Quicken, I beseech thee, most gracious Father, my languid mind, by thy vivifying power,
that I may be more fervent in spirit, earnest in prayer, serving thee faithfully, which,
I can feelingly acknowledge, is my indispensable duty.

[.small-break]
'''

Eleventh month, 1813.--I went to Reading to pay a visit to my brother and sister Maddock,
where I continued till the first month, 1814.
During this time I was often much indisposed,
with frequent returns of violent spasmodic headache,
and trying complaints in my side and stomach, which had continued for years,
and often prevented my assembling with my friends,
to perform that solemn duty of worship, which we owe unto God.
Yet I think I may venture to say, that in these seasons of seclusion,
my mind was frequently brought into a deep concern for the
members of our Society in that part of the vineyard;
and when favoured with ability to avow my allegiance to the Holy Head of the church,
by meeting with my friends, to wait upon and worship him who is a Spirit,
I endeavoured to be faithful, either in doing or suffering,
in which I felt a blessed reward; and a precious evidence was graciously afforded,
that I had been in the way of my duty in paying this visit.
How bountifully are we dealt with, when fully resigned to be any thing or nothing,
just as it pleases unerring wisdom!

The remainder of this year was mostly spent in the endearing
Society of my beloved sisters and friends in the home circle,
and I esteemed this cessation from travelling in the service of Truth,
as an indulgence granted by him, unto whom belong the attributes of love and mercy,
as it gave me the desired opportunity of attending
the sick and dying bed of my much loved sister Rebecca,
who had been for ten years mostly an invalid.
Her disease occasioned great bodily suffering,
which she bore with Christian patience and exemplary fortitude.

On the 5th of tenth month, 1814, the disorder put on a very alarming appearance;
and it was thought by her medical attendants that she could not survive many days; but,
beyond all human probability, she continued, often in a state of indescribable suffering,
for ten weeks,
when the prepared spirit was graciously released from a very afflicted tabernacle.^
footnote:[See an account of this sister at the end.]
The peaceful close which this beloved sister was favoured to experience,
greatly tended to sweeten the bitter cup of separation,
and to strengthen our tried minds to bow, in humble acquiescence, to the divine will,
saying, It is the Lord that giveth and the Lord that taketh away: blessed be his name!
My mind is often brought low in recollecting the privations I have experienced,
in the removal, by death, of many near relatives,
to whom I was closely bound by the ties of nature and grace;
but deeply afflicting as these solemn events have proved,
I dare not entertain a doubt that they were ordered in perfect wisdom and mercy.
In this persuasion I humbly implore divine aid,
to strengthen me to rest in becoming resignation, secretly adopting the language,
"`It is the Lord, let him do as seemeth him good!`"

Every fresh lesson of the great uncertainty of our continuance in mutability,
ought to stimulate to watchfulness and faithfulness.
May this renewed affliction have this effect on my too slothful mind.
Lord, I beseech thee, quicken my feeble endeavours with a holy zeal,
tempered with true knowledge,
that the great work of the day may keep pace with precious time,
which rapidly glides away, and cannot be recalled.

[.small-break]
'''

Sixth month, 1815.--I entered on a family visit to Friends of my own Monthly meeting,
in company with my much esteemed and valued friend William Forster.
We laboured, according to our several gifts, harmoniously, in the love of the gospel,
and were enabled, through the renewed extension of divine aid, in the conclusion,
to commemorate the unmerited mercies of a gracious Lord,
who faileth not to help and preserve those who trust in
him alone,--not daring to lean to their own understandings.
After this I was mostly at home for several months, except spending some time at Staines,
in the fulfilment of social duties in the large family of my afflicted brother-in-law,
Thomas Ashby, who was, in the eighth month of this year, deprived of a second wife,
a truly valuable companion, and kind,
religious care-taker of a numerous family of fourteen children.
I felt the ample reward of peace, in endeavouring to mitigate their trial,
by rendering that little assistance I had in my power, by sympathy and care;
and in performing this and similar duties, I have had cause to say,
it is more profitable to visit the abode of the afflicted,
and mingle the tear of mourning with the sorrowful,
than to enter the habitation of prosperity and mirth.

In the twelfth month, 1815,
I believed my way was opened to leave this interesting family,
having for several years had a prospect of religious service in the counties of Hampshire,
Dorset, Somerset, and the city of Bristol: and having heard that my beloved friends,
William Forster and Sarah Hustler, were under similar concern,
I believed it would contribute most to my peace,
to propose uniting with them in this very important engagement;
which so fully met their concurrence,
that we ventured to spread our religious prospects before our different Monthly meetings:
and obtaining their approbation and sympathy, on the 27th of second month, 1816,
we entered on this weighty embassy, visiting the families of Friends in Bristol,
and most of the meetings in each county; also held public meetings,
as truth appeared to us to open the way.
During the prosecution of this apprehended requiring, faith was often tried,
and I frequently adopted the language, in the secret of my heart,
under a sense of much feebleness, "`Who is sufficient for these things?`"
But through adorable goodness and mercy, I had much occasion gratefully to acknowledge,
that the Lord`'s strength is made perfect in the weakness of his dependent children.
I returned home previous to the Yearly meeting in London, which I was enabled to attend,
though feeble in body.

After this annual solemnity, not finding my mind clear of the meetings in Hampshire,
I attended their Quarterly meeting held at Alton,
from whence I proceeded with my much-loved friends William and Rebecca Byrd,
to such meetings as I felt attracted to in the renewings of gospel love;
and crossed from Lymington to the Isle of Wight,
where we held several meetings with the inhabitants of that small island,
much to our satisfaction, in the belief that there is a precious seed amongst them,
which the great Husbandman is pleased to water with celestial showers.
After taking a few meetings on my return home to our own quiet habitation,
at the end of seventh month, and returning my certificate,
I felt the rich reward of peace and consolation,
raising the language in the secret of my heart:
How good is the Almighty--how worthy to be honoured and obeyed!
On settling down and enjoying the society of my dear sisters,
I had often to feel the great loss we had recently
sustained in the removal of dear John Hull,
a brother justly beloved, who, through the blessed efficacy of divine grace,
had been an elder and father in the militant church,
a sympathizing friend and wise counsellor,
filling a useful station in religious and civil society.
While sorrow covers my mind in the feeling of this privation,
the language of Holy writ sweetly revives,
"`Shall not the Judge of all the earth do right?`"

[.small-break]
'''

The remaining part of this year, and the two following were spent mostly at home,
during which time, I had severe attacks of indisposition,
which instructively proclaimed the necessity of being fervent in spirit,
serving the Lord with all diligence, that a preparation might happily be experienced,
to give up my accounts, when, in the wisdom of God,
the slender thread of life may be broken.
In the latter end of twelfth month, 1818, my serious complaints much increased,
and some alarming symptoms indicated the probability of
the frail body soon yielding to complicated maladies.
This proved a season of much trial, both of faith and patience.
My much-loved sister Martha, was taken dangerously ill,
during the time that I was wholly confined to my bed, and for a season,
it appeared very doubtful whether either of us would again be raised.

In this time of affliction, I used my feeble efforts to seek the Lord and his strength,
much desiring, that by his help and power,
I might possess and manifest Christian patience and resignation,
adopting the language of David, "`Thy judgments, O Lord,
are true and righteous altogether; more to be desired than gold, yea,
than much fine gold: moreover by them is thy servant warned,
and in keeping of them there is great reward.`"
But Oh! the poverty which attended my wading mind,
so that at times little ability seemed to be experienced
to approach the Majesty of Heaven in deep,
heart-felt supplication: truly I could adopt the language of an apostle,
"`Not by works of righteousness which we have done,`" but it must
be through the unmerited mercy of God in Christ Jesus,
if acceptance be our blessed experience in the day of awful decision.

After a long illness of three months, and much proving of mind,
it pleased inscrutable wisdom to raise me again, as from the brink of the grave,
and strengthen both body and mind,
so that I could thankfully utter the language of the Psalmist,
"`The Lord is my light and my salvation, whom shall I fear?
the Lord is the strength of my life, of whom shall I be afraid?`"
Verily, he bringeth low, and raiseth up again at his pleasure:
who shall not trust in his Almighty power, and fear his Holy Name!
After this illness, it was proposed by my medical attendants,
that I should try the effects of warm bathing and sea air;
and apprehending it might also prove beneficial to my beloved sister`'s health,
I consented to go to Hastings as soon as I was able;
and have reason to hope it was not a wrong conclusion, as in a short time,
I was favoured to find considerable improvement,
and was graciously permitted to experience,
that our Almighty Father does not withhold the bread of life,
nor the fresh springs of consolation from those who desire to love and serve him,
in all situations,
however solitary and remote from the outward communion with kindred spirits.

While at this place, separated from society, and free from domestic engagements,
I had great opportunity of viewing and contemplating
the stupendous works of an Almighty Hand,
which loudly proclaim his omnipotence, in the creation of the vegetable world,
and forming the vast deep, causing the raging waves to become a perfect calm,
after a tremendous storm.
Well might David say, "`Oh Lord,
how manifold are thy works! in wisdom hast thou made them all!
The earth is full of thy riches; so is this great and wide sea`"
and with impressions of wonder and gratitude,
he further exclaims, "`I will remember the works of the Lord:
surely I will meditate on all thy works, and talk of all thy doings.`"

Eighth month, 1819, I returned home with my dear sisters.
My mind was fully satisfied with having tried the means recommended,
though it did not prove of such lasting benefit as
our friends and the doctors had hoped for:
yet in the ninth month, 1819, it pleased my Almighty Helper,
to renew my strength sufficiently to enable me to unite with a committee of women Friends,
separated by the Quarterly meeting,
for the important service of visiting the Monthly meetings,
which constitute this large body.
This weighty engagement I was enabled to accomplish,
in conjunction with fellow-labourers, and have gratefully to aknowledge,
that the retrospect yields solid satisfaction, in having endeavoured, though feebly,
to discharge that little debt of love due to the militant church.

[.small-break]
'''

Third month, 1821.--From the conclusion of this service to the present time,
I have mostly been in a very feeble state, not able to go far from home,
and frequently too unwell to attend our religious meetings;
having at times been confined for months together, and not unfrequently to my bed.
And although it is with considerable difficulty I now use my pen,
yet I could not feel easy without leaving a little testimony behind me,
to the mercy and goodness of our compassionate High Priest,
who is ever touched with a feeling of our infirmities,
and does not require more of any of his frail, dependent children,
than he gives them ability to perform, in his own way and time, which must be waited for.
When faith is acted upon, in the fear of the Lord,
and faithfulness keeps pace with revealed duty, the happy result will be,
"`Peace and joy in the Holy Ghost,`"--an ample reward for every sacrifice.
This short remark was penned on recovering from a painful illness of thirteen weeks,
which for some time was so serious,
as again to excite apprehension in my medical attendants,
that the shattered frame would not be able to struggle
through such a load of complicated maladies:
but the Lord my God, hath hitherto sustained both body and mind,
and in the midst of inexpressible suffering, and great poverty of spirit,
has graciously kept in a good degree of patience and resignation to his will,
which I consider an unmerited mercy, vouchsafed in the time of great need.
May my tribulated spirit receive a portion of strength, to lean on the staff of faith,
and renewedly worship, adore, and praise his great and excellent Name,
who is eternally worthy of all honour and renown.
May it be ascribed unto him by me, and may I humbly walk in his fear and counsel,
the few more fleeting days that may be permitted, doubtless in mercy,
that the work may be fully accomplished,
and a preparation known to enter the realms of undisturbed rest and peace,
when the afflictions and temptations, incident to human nature, will forever terminate.

During this long illness, I had much time for reflection and contemplation;
and though at times my dwelling was in a barren land,
where the refreshing influences of divine love are not sensibly felt,
yet in this state I was often brought into near sympathy with the poor and needy,
those who know their faith tried by the withdrawings of the feeling of his presence,
whom they love more than all earthly enjoyments,
and desire more than any perishable object.
Out of weakness, my Amighty Helper strengthened me to crave for such as these,
that not one of them, wherever scattered among the fallen sons of Adam,
or gathered with those who fear the Lord, may be prevailed upon,
by the enemy of their salvation, to let go their confidence in a winter season,
or to make shipwreck of the precious gift of faith,
when the great and wise Pilot may seem to be absent, who, I fully believe,
will not suffer his tried,
dependent children to sink below the mighty waves of discouragement,
which seem ready to overwhelm at such a season.
Oh! how needful for frail mortals to attend to the caution given by our blessed Saviour,
"`Take heed, that your flight be not in the winter, or on the sabbath day!`"
My mind was also brought to feel for the whole human race,
and desires were raised in my heart, that the day might be hastened,
when the glorious prophecy shall be fulfilled,
"`The earth shall be full of the knowledge of the Lord, as the waters cover the sea.`"
Surely in that happy day, the cruelty of man will cease,
and oppression towards fellow mortals, or the brute creation, will be known no more,
but the harmonizing influence of divine love will be the main spring of every action,
and works of righteousness will be in accordance with that angelic language,
"`Glory to God in the highest, peace on earth, and good will to men.`"

[.small-break]
'''

Since the last memorandums were penned, to the present date, eleventh month, 1822,
it has pleased unerring wisdom, to dispense an increased portion of bodily suffering,
which nothing short of divine aid could have enabled me to bear,
with any degree of patience and resignation; but I may thankfully say,
through the unmerited mercy of a gracious God,
holy help has been so afforded in the needful time, that I feel a consoling hope,
that my mind has been preserved from any degree of murmuring under the present,
and various other dispensations of my tribulated life;
nor have I ever dared to ask that those bitter cups might be removed from me,
until they had fully accomplished the design of him who afflicteth not willingly,
but for the blessed purpose of the sanctification of the immortal spirit.
Oh! that the sufferings dispensed in pure, unerring wisdom,
to one of the weakest and most unworthy of the Lord`'s children,
may have the effect of preparing for a resting place
amongst those "`who have passed through great tribulation,
and have known their robes washed and made white, in the blood of the immaculate Lamb!`"

In deep abasement of mind, I can truly say, I have not asked riches, honour,
or length of days, but for an understanding heart,
to fulfill my religious and civil duties with acceptance:
and though I can very feelingly acknowledge myself an unprofitable servant,
not worthy to bear testimony to the never-failing
mercies and goodness of my heavenly Father,
yet for the encouragement of others, I feel bound, in a sense of heart-felt gratitude,
to acknowledge that there is a rich reward attached
to an honest endeavour to employ our time and talents,
in the service of our great Creator, in that way and manner, manifested to us,
by the light of the Holy Spirit, which leadeth out of error, into "`all truth.`"
Oh! how often is my exercised mind brought into tender feeling for my fellow mortals!
I long, with earnest solicitude, that all the human race might come to embrace the Truth,
as it is in Jesus Christ, the Redeemer of degenerate man; that salvation through him,
might happily be experienced; and the blessed result of believing and obeying,
eternally enjoyed:
then will the end of a probationary life be crowned with enduring peace and joy.
How unspeakable are the advantages of unreserved faithfulness,
and humble dedication of heart; sacrifices that are well pleasing to an Omniscient God,
who does not fail to support the dependent mind, in all its tribulations,
and at seasons graciously affords a lively hope,
that the afflictions of the present time, if patiently borne,
will work for us a "`far more exceeding and eternal weight of glory.`"
Above all things I desire to be kept in that state of perfect resignation,
which breathes the language taught us by Christ, our great example, "`Not as I will,
but as thou wilt!`"--not my will, but thine be done.
Oh Father!

[.small-break]
'''

Eleventh month, 1824.--I am fully aware that much has been written, and much spoken,
by experienced servants of the Lord Jesus, in the demonstration of the Spirit,
which giveth understanding to such of his humble dependent
children as are truly desirous of receiving heavenly counsel;
yet I am afraid, of falling short of that which I owe to a good and gracious Creator,
did I not endeavour, though under much bodily weakness, to exalt His power,
by bearing testimony with my pen to his never-failing mercy and grace,
to support through a long protracted season of suffering, both of flesh and spirit.
And although it has pleased unerring wisdom thus to try my faith,
I have abundant cause thankfully to acknowledge the efficacy of that word of power,
which calmed the raging waves of affliction, by the gracious language, "`Peace,
be still!`"
And now, the remembrance of the Lord`'s dealings with his unworthy servant,
bows my soul in gratitude and praise,
and an earnest desire is felt to commemorate his love:
and may the expression animate and encourage fellow candidates for a crown immortal,
to seek after, and implicitly trust in,
that Holy Being who is Omnipotent and Omnipresent,
ever manifesting a fatherly care over the workmanship of his hand.
In a renewed sense of his never-failing mercies, my mind is led to crave for thousands,
and tens of thousands of my fellow creatures, of every nation, kindred,
tongue and people, that they may come to the knowledge of the Lord our God,
and Jesus Christ, our blessed Redeemer, and Mediator;
that they may come to know the happy effects of believing in, and obeying,
that Word of power, which is nigh in the heart, convincing of evil,
and manifesting our religious and moral duties.
How affectionately do I desire that those in early life, of every description,
who are objects of my tender and earnest solicitude,
may choose the Lord for their portion,
and the God of Jacob for the lot of their inheritance;
that by a strict attention to the Spirit of Christ,
and obedience to the gradual unfoldings of divine counsel,
they may become qualified to show forth his praise:
then will the many gracious promises left upon sacred record for
the instruction and encouragement of the humble and sincere Christian,
be verified in their joyful experience:
the Lord their God will delight to bless them with
the frequent incomes of His light and life.
He will be unto them a rock of defence in every season of conflict,
a gracious preserver in the day of prosperity,
and the everlasting source of effectual help and consolation, in times of adversity;
so that "`neither heights nor depths,`" nor any of
the varied dispensations of unerring wisdom,
"`will ever be able to separate them from the love of God,
which is in Christ Jesus our Lord.`"

[.asterism]
'''

In the early part of the year 1825 this deeply tried
servant of Christ was laid on a bed of sickness,
with little expectation of being raised from it.
Her complaints assumed a serious character, and were attended with very acute pain.
When speaking of her sufferings, she remarked,
"`The dispensations of inscrutable wisdom are all in love and mercy,
and it is for us dependent beings to say in truth and sincerity, '`Thy will be done.`'`"
In the course of the summer she so far recovered as to go a short distance from home,
and attended two meetings,
in which she was enabled to exert her weak bodily
powers in advocating the cause most dear to her.
In the first month following, she was again confined to her bed, and suffered much pain,
which she endured with great patience;
desiring that the divine will might be fully accomplished, and often said,
she felt poor and needy,
but her hope and trust in redeeming love and mercy were unshaken.
She continued to evince a lively interest in the concerns and best welfare of her friends,
and in times of religious retirement with them, she imparted Christian instruction,
when too weak to be raised in her bed.
On one occasion, after having been much exhausted, and when apparently sinking fast,
she said, "`My countenance appearing distressed, does not indicate distress of mind:
pain of body will distress the countenance;`" and then added,
"`Thy will be done! thy blessed will be done!
O, my soul, praise the Lord! bless and magnify His Name!`"
On being asked if she was comfortable, she replied,
"`All is comfort;`" and at another time said,
that her great affliction had been abundantly made up,
and that help had been extended in the needful time.

She also expressed a wish that the language might be accepted,
"`Now let thy servant depart in peace, for mine eyes have seen thy salvation.`"
Some time after she said, "`If it were the Lord`'s blessed will to release me,
it would be cause of thankfulness;`" and she expressed an
humble hope that a place of rest was prepared for her.
During the last few weeks of her life her breathing was so much affected,
as to make it difficult for her to say much without producing spasms,
which were very distressing,--One day she said, "`Though I cannot express much,
I feel holy quiet.`"
The day preceding her release was one of extreme suffering; and in the evening,
a friend taking leave of her, she said, "`If I am gone in the morning,
there will be cause to rejoice.`"
The forepart of the night she became easier, and on the following day, the month, 1826,
she gradually sunk away in great quietness:--and her purified spirit,
we may consolingly believe, was, through the mercy of God in Jesus Christ,
received into a heavenly mansion, to joy unspeakable and full of glory.

[.asterism]
'''

Earlier in this publication there is a notice of Rebecca Crowley,
sister of Ann Crowley, who was, for ten years, mostly an invalid.
Her disorder occasioned great pain, which she bore with Christian patience.
On the 5th of tenth month, 1814, it assumed an alarming appearance,
and it was thought by her medical attendants, that she could not survive many days; but,
beyond all human probability, she continued, often in a state of indescribable suffering,
for ten weeks.
During this time,
her great composure of mind evinced that her hope
and trust were firmly fixed on the Lord:
and though it pleased him, often to permit her to be tried with poverty of spirit,
yet she said, "`It is a great favour to feel a precious quiet.`"

She manifested much love and tender concern for her relations and friends,
to several of whom she gave suitable advice, particularly to her nephews and nieces,
and some young friends, who called to see her,
impressing them with the necessity of preparing for such an afflictive dispensation,
saying, it was dangerous to put off, for, at such a trying time,
the pains of the body seemed enough to bear.

She very tenderly advised a young friend to be faithful
in giving up to little things that were made manifest,
saying,
"`None of the pleasures or gratifications of this world are worthy
to be compared with true peace of mind at such a time as this,
when little things appear great things.`"
She several times expressed a desire to be preserved from speaking what she did not feel,
saying, it was not the shadow, but the substance of religion, that would prove availing.
At times, when her pain was a little alleviated,
she requested her sister to read some portion of Scripture, which, she said,
had a calming influence on her mind.

One morning, on being asked how she had passed the night, she replied,
"`I have been in much pain, and felt poor and low in spirit;
but after a few minutes sleep, towards morning, I awoke with these expressions,
'`A bruised reed shall he not break, and the smoking flax shall he not quench,
till he send forth judgment unto victory.`' This
afforded a little comfort to my tried mind.`"
After one of her sisters had been reading on first-day evening,
she expressed the great comfort she had felt in their being together;
and affectionately embracing each, she expressed her desire that they might so live,
as to afford the consoling hope of meeting again in the mansions of rest and peace.
At another time, when under great bodily suffering, she said,
"`This is pain indeed;`" and requested her sisters to pray for her,
that her patience might hold out to the end.
To one of them she said, "`I have been thinking much of poor Job;
and can adopt the language of Samuel Fothergill,
'`Tedious days and wearisome nights are appointed unto me.`'`"

On the 13th of twelfth month, she became more alarmingly ill,
which excited apprehensions that her final change was approaching.
On again reviving a little, she sweetly broke forth, "`I humbly thank thee.
Oh, dearest Father! for this great favour,
in granting me the opportunity of taking leave of my dear sisters and giving them the
satisfaction of knowing that I now feel an evidence of entering into rest.
Now I may tell you, my beloved sisters, for your consolation,
that I have a prospect of entering into glory.`"
This was uttered with a melodious and audible voice;
the sweetness of her countenance bespeaking the heavenly frame of her mind,
and the precious feeling that attended was inexpressible.
She also said, "`Though I have thus expressed myself, I would not have you think,
that I do not feel it an awful thing to die;--an awful thing
to appear before the Judge of the whole earth,
who doeth all things right.`"
She expressed to a brother,
that although she had led what might be termed an innocent life,
yet she had found much to repent of,
but expressed her belief that she had been forgiven.^
footnote:[When we contemplate the high standard set before us by our blessed Saviour,
"`Be ye therefore perfect, even as your Father,
which is in heaven is perfect,`" Matt. 5:48; and on the other hand,
the declaration of the apostle, "`He that knoweth to do good, and doeth it not,
to him it is sin;`" and when we consider that,
under an entire submission to the renovating power of the Holy Spirit,
"`every thought is to be brought into captivity to
the obedience of Christ,`" 2 Cor. 10:5;
are we not, in deep humiliation, prepared to acknowledge, that however innocent,
in the view of men, we have much need of forgiveness,
and that we have no ground of safe confidence but in the mercy of God in Christ Jesus.
This was known to be the case with our dear friend,
and accords with her dying expressions, "`Come, dear Jesus!
I am ready.`"]

Her dissolution drawing near, after a short pause, she said,
"`Now I should like to bid my sisters affectionately
farewell;`" which she did in a very moving manner,
encircling them in her arms; suitably addressing them separately; and saying,
what a consolation it had been, to have them all with her in this illness; and also,
what a comfort it was, that they had lived together in love and peace.
After this,
she took an affectionate and grateful leave of her medical
attendant and the servant who had waited upon her.
Soon after, enquiring who were in the room, and being told, her sisters, she requested,
if not imposing too much on their feelings, that they would not leave her,
asked what time it was; and finding some hours had elapsed while watching round her bed,
desired they would take refreshment, saying,
she believed the time was nearly come for her release,
and she did not know how soon it might be, or that she might express much more;
but presently after said, "`Come, dear Jesus!
I am ready;`" and desired those present, to unite in supplicating for a speedy release;
yet she soon added,
that she wished to wait in patience and resignation the appointed time.
She requested her interment might be in a plain simple way;
that her sisters might be at liberty to feel after that quietude and retirement of mind,
so desirable at such a time; adding, "`I hope it will prove a solemn day to you.`"

A time of great suffering ensued, under which, with uplifted hands,
she petitioned to be spared another such attack,
if consistent with his will who designed her sanctification,
and requested her sisters would pray that she might have an easy passage,
which she believed would be granted her.
During the night she had some quiet sleep, and appeared considerably relieved from pain,
for which she feelingly acknowledged her sense of gratitude.
About seven in the morning, signs of dissolution appeared, and on being lifted up,
she gently reclined her head on one side, and ceased to breathe.
Thus was her humble prayer mercifully granted, and the prepared spirit,
leaving its afflicted tabernacle, took its flight, there is no doubt,
to a habitation among the saints in light,
forever to enjoy that glorious rest of which she had so clear a prospect.
